import { toLocalDateInputValue } from '../../utils/formatters';
import React, { useState } from 'react';
import {
  X,
  CheckSquare,
  Calendar,
  User,
  CheckCircle,
  Tag,
} from 'lucide-react';
import { useApp } from '../../context/AppContext';
import { AssignmentPriority, MaterialTask } from '../../types';

interface AddTaskModalProps {
  initialStudentId?: string;
  writtenExamId?: string;
  preparationId?: string;
  onClose: () => void;
}

export const AddTaskModal: React.FC<AddTaskModalProps> = ({
  initialStudentId,
  writtenExamId,
  preparationId,
  onClose,
}) => {
  const { students, addTask } = useApp();
  const activeStudents = students.filter((s) => !s.isArchived);

  const [title, setTitle] = useState('');
  const [studentId, setStudentId] = useState(initialStudentId || '');
  const [category, setCategory] = useState<MaterialTask['category']>('Genel Görev');
  const [dueDate, setDueDate] = useState(toLocalDateInputValue());
  const [priority, setPriority] = useState<AssignmentPriority>('Normal');
  const [description, setDescription] = useState('');

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!title.trim()) return;

    addTask({
      title,
      studentId: studentId || undefined,
      category,
      dueDate,
      priority,
      status: 'Yapılacak',
      isAutoGenerated: false,
      description,
      writtenExamId,
      preparationId,
    });

    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/70 backdrop-blur-sm flex items-center justify-center p-3 sm:p-4 overflow-y-auto animate-in fade-in">
      <div className="bg-white dark:bg-slate-900 rounded-3xl max-w-lg w-full my-6 p-6 shadow-2xl border border-slate-200 dark:border-slate-800 space-y-5">
        {/* Header */}
        <div className="flex items-center justify-between border-b border-slate-100 dark:border-slate-800 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-2xl bg-rose-600 text-white flex items-center justify-center font-bold shadow-md shadow-rose-500/20">
              <CheckSquare className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-lg font-black text-slate-900 dark:text-white font-display">
                Yeni Materyal & Görev Ekle
              </h3>
              <p className="text-xs text-slate-500">
                Föy hazırlama, soru seçimi, veli araması veya yazılı hazırlığı görevi tanımlayın
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-2 rounded-xl text-slate-400 hover:text-slate-600 hover:bg-slate-100 dark:hover:bg-slate-800"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        <form onSubmit={handleSubmit} className="space-y-4">
          {/* Title */}
          <div className="space-y-1">
            <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Görev Başlığı *
            </label>
            <input
              type="text"
              required
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Örn: 8. Sınıf Kareköklü Sayılar 20 Soruluk Yeni Nesil Föyü Hazırla"
              className="w-full text-xs p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 focus:outline-none font-medium"
            />
          </div>

          {/* Student & Category */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                İlişkili Öğrenci (İsteğe Bağlı)
              </label>
              <select
                value={studentId}
                onChange={(e) => setStudentId(e.target.value)}
                className="w-full text-xs p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 focus:outline-none"
              >
                <option value="">Konu Özeti / Tüm Öğrenciler</option>
                {activeStudents.map((s) => (
                  <option key={s.id} value={s.id}>
                    {s.firstName} {s.lastName} ({s.gradeLevel})
                  </option>
                ))}
              </select>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Kategori
              </label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value as MaterialTask['category'])}
                className="w-full text-xs p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 focus:outline-none font-medium"
              >
                <option value="Test Hazırlığı">Test Hazırlığı</option>
                <option value="Tekrar Föyü">Föy / Ders Notu Hazırlama</option>
                <option value="Yazılı Provası">Okul Yazılı Soruları</option>
                <option value="Çalışma Kağıdı">Çalışma Kağıdı</option>
                <option value="Konu Özeti">Konu Özeti</option>
                <option value="Genel Görev">Genel Görev</option>
              </select>
            </div>
          </div>

          {/* Priority & Due Date */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Öncelik
              </label>
              <select
                value={priority}
                onChange={(e) => setPriority(e.target.value as AssignmentPriority)}
                className="w-full text-xs p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 focus:outline-none font-medium"
              >
                <option value="Yüksek">🚨 Yüksek Öncelikli (Acil)</option>
                <option value="Normal">🟡 Normal Öncelikli</option>
                <option value="Düşük">🟢 Düşük Öncelikli</option>
              </select>
            </div>

            <div className="space-y-1">
              <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
                Son Tarih *
              </label>
              <input
                type="date"
                required
                value={dueDate}
                onChange={(e) => setDueDate(e.target.value)}
                className="w-full text-xs p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 focus:outline-none"
              />
            </div>
          </div>

          {/* Description */}
          <div className="space-y-1">
            <label className="text-xs font-bold text-slate-700 dark:text-slate-300">
              Açıklama / Detaylar
            </label>
            <textarea
              rows={2}
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Materyalin içeriği veya yapılacaklar..."
              className="w-full text-xs p-2.5 rounded-xl bg-slate-50 dark:bg-slate-800 border border-slate-200 dark:border-slate-700 focus:outline-none resize-none"
            />
          </div>

          {/* Submit Actions */}
          <div className="flex items-center justify-end gap-2 pt-2 border-t border-slate-100 dark:border-slate-800">
            <button
              type="button"
              onClick={onClose}
              className="px-4 py-2.5 rounded-xl border border-slate-200 dark:border-slate-700 text-xs font-bold text-slate-600 dark:text-slate-300 hover:bg-slate-50 dark:hover:bg-slate-800"
            >
              İptal
            </button>
            <button
              type="submit"
              className="px-6 py-2.5 rounded-xl bg-rose-600 hover:bg-rose-700 text-white text-xs font-bold shadow-md shadow-rose-600/20 flex items-center gap-2 transition-all active:scale-95"
            >
              <CheckCircle className="w-4 h-4" />
              <span>Görevi Kaydet</span>
            </button>
          </div>
        </form>
      </div>
    </div>
  );
};
