create table if not exists public.push_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  endpoint text not null,
  p256dh text not null,
  auth text not null,
  user_agent text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, endpoint)
);
alter table public.push_subscriptions enable row level security;
grant select, insert, update, delete on public.push_subscriptions to authenticated;
create policy "push own select" on public.push_subscriptions for select to authenticated using ((select auth.uid()) = user_id);
create policy "push own insert" on public.push_subscriptions for insert to authenticated with check ((select auth.uid()) = user_id);
create policy "push own update" on public.push_subscriptions for update to authenticated using ((select auth.uid()) = user_id) with check ((select auth.uid()) = user_id);
create policy "push own delete" on public.push_subscriptions for delete to authenticated using ((select auth.uid()) = user_id);

create table if not exists public.push_delivery_log (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  lesson_id text not null,
  lead_minutes integer not null,
  lesson_date text not null,
  sent_at timestamptz not null default now(),
  unique(user_id, lesson_id, lead_minutes, lesson_date)
);
alter table public.push_delivery_log enable row level security;
revoke all on public.push_delivery_log from anon, authenticated;
